### ISSUE TITLE
error: unexpected token in '.section' directive

### ISSUE THREAD

**Issue by magnified103** [iains/gcc-12-branch#17] opened 2023-02-01 12:06 UTC
I'm trying to build this snippet under GCC 12.2 (homebrew) on macOS 13

```cpp
#include <vector>

std::vector<int> arr[100000];

int main() {}
```

Build:

```shell
$ g++-12 -o main main.cpp
/var/folders/bc/8mk4ndsx2zl7qxxvdnjccr540000gn/T//ccXt4STq.s:445:29: error: unexpected token in '.section' directive
        .section .data.rel.ro.local
```

It seems that the error does not occur with `-O2` flag.

<details>
<summary>g++-12 -v</summary>

```shell
Using built-in specs.
COLLECT_GCC=g++-12
COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/aarch64-apple-darwin22/12/lto-wrapper
Target: aarch64-apple-darwin22
Configured with: ../configure --prefix=/opt/homebrew/opt/gcc --libdir=/opt/homebrew/opt/gcc/lib/gcc/current --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-12 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-zstd=/opt/homebrew/opt/zstd --with-pkgversion='Homebrew GCC 12.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --with-system-zlib --build=aarch64-apple-darwin22 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Homebrew GCC 12.2.0) 
```
</details>

**Comment by iains** [comment] 2023-02-01 12:20
confirmed.

It looks like the code (at O0) saves the end position of the array as a constant (.data.rel.ro.local is constant data section on ELF, but **not** for Mach-O).  At O1 and above the value is computed in-line (so that it does not try to create the constant in that section).

Oddly, it looks like we compute the end address of smaller arrays in-line even at O0 (so it will be a case of tracking down where this decision is made, and then making sure that we emit a suitable section designator for macOS / Mach-O).

**Comment by Season0518** [comment] 2023-05-09 07:55
This issue still exists on gcc13. I have attempted to downgrade to gcc11 and the issue has been resolved.

**Comment by iains** [comment] 2023-05-27 12:18
fixed on this branch now.

**Closed as completed by iains** 2023-05-27 12:18 UTC
